config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show] 

  get 'posts/date' => 'posts#date'
  get 'posts/travel' => 'posts#travel'
  get 'posts/cafe' => 'posts#cafe'
  get 'posts/top' => 'posts#top'
  get 'posts/images' => 'posts#images'

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  get 'lectures/index'
  get 'lectures/new'

 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'posts#index'
   
    end
    

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

    #tweetsテーブルから中間テーブルに対する関連付け
  has_many :post_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
   
  # 以下を追記
  validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :post_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts       
         has_many :posts, dependent: :destroy 
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }
         
         has_many :likes, dependent: :destroy
         has_many :liked_posts, through: :likes, source: :post
         def already_liked?(post)
          self.likes.exists?(post_id: post.id)
        end
        mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys:  [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
      
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:top]
  
  def top
    
  end

 
    def index

        if params[:tag]
          Tag.create(name: params[:tag])
        end
        
        if params[:tag_ids]
          @posts = []
          params[:tag_ids].each do |key, value|
            if value == "1"
              tag_posts = Tag.find_by(name: key).posts
              @posts = @posts.empty? ? tag_psots : @posts & tag_psots
            end
          end
        end

    end

    def index
      
      @posts = Post.all

      @posts = Post.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}

    end

    def new
        @post = Post.new
    end
    
      def show
        @post = Post.find(params[:id])
      end

      def date
        @dates = Post.where(category:"date") #ここがポイント！categoryのバリューがdogの投稿を取得！
      end
    
      def travel
        @travels = Post.where(category:"travel") #ここがポイント！categoryのバリューがcatの投稿を取得！
      end
    
      def cafe
        @cafes = Post.where(category:"cafe") #ここがポイント！categoryのバリューがhadakadebanezumiの投稿を取得！
      end

      def edit
        @post = Post.find(params[:id])
      end

      def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end

      def create
        post = Post.new(post_params)
       
        post.user_id = current_user.id

        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      private
      def post_params
        params.require(:post).permit(:cotent, :image, :category, :evaluations, :comments, :body, tag_ids: [])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wherewear</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8aef82f3ca.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>


  </body>

</html>

app/views/lectures/index.html.erb
<h1>Lectures#index</h1>
<p>Find me in app/views/lectures/index.html.erb</p>

app/views/lectures/new.html.erb
<h1>Lectures#new</h1>
<p>Find me in app/views/lectures/new.html.erb</p>

app/views/posts/cafe.html.erb
<header>
  <h1>Where Wear</h1>
  <div class="header-list">
    <ul>
      <li><%= link_to "Back", posts_path %></li>
    </ul>
  </div>
</header>

<link rel="stylesheet" href="date.scss">

<section id="cafe-block">
  <!-- Content for cafe-block can be added here -->
</section>

<section id="date-block">
  <h3>投稿一覧</h3>
  <br>
  <div class="date">
    <% @cafes.each do |t| %>
      <div class="post-entry">
        <%= image_tag t.image_url, size: "345x395" if t.image? %>
        <p><%= link_to t.user.name, user_path(t.user.id) %></p>
        <%= link_to "Detail", post_path(t.id) %>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/date.html.erb
<header>
  <h1>Where Wear</h1>
  <div class="header-list">
    <ul>
      <li><%= link_to "Back", posts_path %></li>
    </ul>
  </div>
</header>

<link rel="stylesheet" href="date.scss">

<section id="love-block">
  <!-- Content for love-block can be added here -->
</section>

<section id="date-block">
  <h3>投稿一覧</h3>
  <br>
  <div class="date">
    <% @dates.each do |t| %>
      <div class="post-entry">
        <%= image_tag t.image_url, size: "345x395" if t.image? %>
        <p><%= link_to t.user.name, user_path(t.user.id) %></p>
        <%= link_to "Detail", post_path(t.id) %>
        
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/edit.html.erb
<body>

<header>

    <h1>Where Wear</h1>
    <div class="header-list">
      <ul>
       <li><%= link_to "Back", posts_path %></li>
      </ul>
    </div>
    
</header>

<link rel="stylesheet" href="edit.scss">

<section id="edit-block">

<div class="edit">
  <div class="picture">
  <p><%= image_tag @post.image_url, size: "450x550" if @post.image? %></P>
  </div>

  <%= form_for @post do |f| %>

  <div class="editer">
   <p><%= f.label :edit %></P>
   <%= f.text_field :comments, :size => "60x100" %> 
   <br>
   <br>
   <p> <%= f.submit "編集する" %>
  </div>
    <% end %>

</div>
<br>
<br>

</section>

</body>

app/views/posts/event.html.erb
<h1>イベント参加時コーデ</h1>

<div class="posts-container">
<% @events.each do |t| %>
  <div class="post">
    <%= link_to t.user.name, user_path(t.user.id) %> 
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.comments %>
    <%= t.created_at %>
    <%= t.category %>
    
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
<% end %>

    <%= link_to "詳細へ", post_path(t.id) %>
    <%= link_to "編集する", edit_post_path(t.id) %>
    <%= button_to "削除する", post_path(t.id),  method: :delete %>  
    <div>
    
</div>

<% end %>

app/views/posts/index.html.erb
<header>

    <h1>Where Wear</h1>
    <div class="header-list">
      <ul>
        <li><%= link_to "Cafe", posts_cafe_path %></li>
        <li><%= link_to "Travel", posts_travel_path %></li>
        <li><%= link_to "Date", posts_date_path %></li>
        <li><% if user_signed_in? %> <%= link_to "MY PAGE", user_path(current_user.id) %><% end %></li>
        <li><%= link_to 'NEW POST', new_post_path %></li>
        <li><%= button_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
    
</header>

<link rel="stylesheet" href="index.scss">

<section id="index-block"> 

</section>

<section id="homme-block"> 

<h3>投稿一覧</h3>
<br>

<div class="date">

<% @posts.each do |t| %>
  
       <div class="dddd">

       <%= image_tag t.image_url, size: "345x395" if t.image? %>
      
       <p><%= link_to t.user.name, user_path(t.user.id) %></p>
          <%= link_to "Detail", post_path(t.id) %>
          <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
          <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
          <% else %>
          <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
          <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
          <% end %>
          <% else %>

          <i class="far fa-heart">
          </i><%= t.likes.count %>
          <% end %>
       
      </div>
      
  <% end %>

</div>

</section>

app/views/posts/new.html.erb
<section id="second-block">

<body>

<header>

    <h1>Where Wear</h1>
    <div class="header-list">
      <ul>
       <li><%= link_to "Back", posts_path %></li>
      </ul>
    </div>
    
</header>

<link rel="stylesheet" href="new.scss">

      
<div class="form">
  <%= form_for @post do |f| %>
  <div class="submit">
     <div class="image">
       <%= f.label :image %>
       <br>
       <%= f.file_field :image, id:"file-input",onchange:"previewImage()" %>
       <img id="image-preview" src="#" alt="Image Preview" hidden/>
     </div>
     
     <div class='form-group'>

      <%= f.label :Comments %>
      <br>
      <%= f.text_field :comments, :size => 50%>
      <p>scene</P>
      <%= f.select :category, [["date", "date"], ["travel", "travel"], ["cafe", "cafe"]], include_blank: "どの投稿？" %>
      <end> 
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>

    <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
          <% end %>  
    </div>
      
      <% end %>
      <%= f.submit "投稿する" %>
  </div>
  <% end %>
     
</div>  

</section>

<script>
  // プレビュー表示
  const previewImage = () => {
    const fileInput = document.getElementById("file-input");
    const imagePreview = document.getElementById("image-preview");

    if (fileInput.files && fileInput.files[0]) {
      const reader = new FileReader();
      reader.onload = (e) => (imagePreview.src = e.target.result);
      reader.readAsDataURL(fileInput.files[0]);
      imagePreview.hidden = false;
    }
  };
</script>

app/views/posts/show.html.erb
<body>
  <header>
    <h1>Where Wear</h1>
    <div class="header-list">
      <ul>
        <li><%= link_to "Back", posts_path %></li>
      </ul>
    </div>
  </header>

  <section id="detail-block">
    <div class="shown">
      <div class="show">
        <p><%= image_tag @post.image_url, size: "450x550" if @post.image? %></p>
        <p><%= @post.created_at %></p>
        <% @post.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(@post) %>
            <%= button_to post_like_path(@post), method: :delete do %>
              <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(@post), method: :post do %>
              <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
      </div>

      <div class="poster">
        <h2>Comments</h2>
        <p><%= @post.comments %></p>
        <br><br><br>
        <h2>いいねしたユーザー</h2>
        <% @post.liked_users.each do |user| %>
          <li><%= user.email %></li>
        <% end %>
        <%= link_to "Edit", edit_post_path(@post.id) %>
      </div>
    </div>
  </section>
</body>

app/views/posts/top.html.erb
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="top.scss">
  </head>

<body>
  <header class="header-nav">
    <h1>Where Wear</h1>
  
    <div class="header-list">
      <ul>
       <li><%= link_to "LOGIN", posts_path %></li>
       <li><%= link_to "SING UP", new_user_registration_path %><li>
      </ul>
    </div>
     
  </header>

    <section id="one-block"> 
      <div class="text-container">
       <b>Where×Wear<b>
      </div>

    </section>

    <section id="two-block">
      <br>
      <br>
      <h3>About.</h3>
      <br>
      <div class="About">

        <div class="t-shirts">
          <%= image_tag ("t-shirts.png"), size: '320x320' %>
          <style>
          border-radius: 10px 30px 0 40px;
          </style>
        </div>
        
        <div class="ttt">
             <p>場所・場面に特化したファッション投稿サイト<p>
             <br>
          <h2>Where×Wear</h2>
             <br>
             <p>(場所)×(着る)</p>
        </div>

      </div>

    </section>

    <section id="three-block">
    <br>
    <br>
    <h3>Outfit</h3>
    <br>
    <br>
      <div class="wrap slide-paused" ontouchstart="">
      
       <ul class="slideshow">
         <li class="content"><%= image_tag ("masaya.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("go.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("street.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("me.jpg"), size: '330x320' %></li>
       </ul>
       <ul class="slideshow">
         <li class="content"><%= image_tag ("masaya.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("go.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("street.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("me.jpg"), size: '330x320' %></li>
       </ul>
       <ul class="slideshow">
         <li class="content"><%= image_tag ("masaya.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("go.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("street.jpg"), size: '330x320' %></li>
         <li class="content"><%= image_tag ("me.jpg"), size: '330x320' %></li>
       </ul>
      </div>
  
    </section>


    <section id="four-block">
      <br>
      <br>
      <h3>Profile.</h3>
      <br>
      <br>
      <div class="Profile">
        
        <div class="imagess">
          <%= image_tag ("yyy.jpg"), size: '320x320' %>
        </div>

        <div class="profi">
          <h3>YUSHI</h3>
          <br>
          <b>長崎県出身。大学3年生。<b>
          <br>     
          小学校から高校まで10年間野球を続け、
          <br>
          大学時代はアパレル店でアルバイトしていました。
          <br>
          洋服への愛は誰にも負けません。
        </div>

      </div>

    </section>

    <footer>
      <p>Copyright © Where×Wear All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/travel.html.erb
<header>
  <h1>Where Wear</h1>
  <div class="header-list">
    <ul>
      <li><%= link_to "Back", posts_path %></li>
    </ul>
  </div>
</header>

<section id="travel-block"> 
  <!-- Travel content can be added here -->
</section>

<section id="date-block">
  <h3>投稿一覧</h3>
  <br>
  <div class="date">
    <% @travels.each do |t| %>
      <div class="post-entry">
        <%= image_tag t.image_url, size: "345x395" if t.image? %>
        <p><%= link_to t.user.name, user_path(t.user.id) %></p>
        <%= link_to "Detail", post_path(t.id) %>
        
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>

<!--link_to "Sign up",  new_user_registration_path(resource_name) --><br />

<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?",  new_user_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<body>

<header>

    <h1>Where Wear</h1>
    <div class="header-list">
      <ul>
       <li><%= link_to "BACK.", posts_path %></li>
      </ul>
    </div>
    
</header>

<link rel="stylesheet" href="my page.scss">

<div class="pro">
<div class="namer">
  <div class="proga">
   <%= image_tag @user.image_url, size: "250x200" if @user.image? %>
  </div>
    <h5>Name : <%= @user.name %></h5>
    <h5>E-mail : <%= @user.email %></h5>
    <h5>Profile : <%= @user.profile %></h5>
    <% if current_user.id == @user.id %>
    <h6><%= link_to "Edit", edit_user_registration_path %></h6>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <h2>投稿一覧</h2>

  <div class="date">
  
<% @user.posts.each do |t| %>
  
  <div class="dddd">

  <%= image_tag t.image_url, size: "345x395" if t.image? %>
 
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
     <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
       <i class="fas fa-heart"></i><%= t.likes.count %>
     <% end %>
     <% else %>
     <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
     <i class="far fa-heart"></i><%= t.likes.count %>
     <% end %>
     <% end %>
     <% else %>

     <i class="far fa-heart">
     </i><%= t.likes.count %>
     <% end %>

     <%= button_to "Delate", post_path(t.id), method: :delete %>
     <%= link_to "Detail", post_path(t.id) %>
     <% if user_signed_in? && current_user.id == t.user_id %>
     <%= link_to "Edit", edit_post_path(t.id) %>

      <% end %> 

 </div>


 
<% end %>

  
  
</div>